// src/lib/mockData/skuData.ts
// 商家 SKU 数据：每个商家的真实在售商品清单

import { SkuData } from '@/types'

export const insta365Skus: SkuData[] = [
  {
    id: 'insta_001',
    name: 'Insta360 X5 运动相机',
    price: 499,
    cost: 275,
    weeklySales: 48,
    weeklyGMV: 23952,
    stock: 180,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 26,
    marginRate: 0.45,
    fieldMix: { creatorContent: 65, sellerContent: 20, shopTab: 10, search: 5 },
    isStar: true,
  },
  {
    id: 'insta_002',
    name: '运动相机挂脖支架套装',
    price: 29,
    cost: 11.6,
    weeklySales: 82,
    weeklyGMV: 2378,
    stock: 250,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 21,
    marginRate: 0.60,
    fieldMix: { creatorContent: 40, sellerContent: 30, shopTab: 20, search: 10 },
    isStar: true,
  },
  {
    id: 'insta_003',
    name: '256GB 高速 TF 卡套装',
    price: 49,
    cost: 32,
    weeklySales: 60,
    weeklyGMV: 2940,
    stock: 300,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 35,
    marginRate: 0.35,
    fieldMix: { creatorContent: 30, sellerContent: 25, shopTab: 25, search: 20 },
    isStar: false,
  },
  {
    id: 'insta_004',
    name: '40米防水潜水壳',
    price: 79,
    cost: 35,
    weeklySales: 32,
    weeklyGMV: 2528,
    stock: 60,
    stockHealth: 'low',
    type: 'seasonal',
    salesTrend: 'up',
    turnoverDays: 13,
    marginRate: 0.55,
    fieldMix: { creatorContent: 70, sellerContent: 15, shopTab: 10, search: 5 },
    isStar: false,
  },
  {
    id: 'insta_005',
    name: '迷你三脚架自拍杆',
    price: 19,
    cost: 6.6,
    weeklySales: 120,
    weeklyGMV: 2280,
    stock: 400,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 23,
    marginRate: 0.65,
    fieldMix: { creatorContent: 50, sellerContent: 20, shopTab: 20, search: 10 },
    isStar: true,
  },
  {
    id: 'insta_006',
    name: '360° 镜头保护罩',
    price: 15,
    cost: 4.5,
    weeklySales: 95,
    weeklyGMV: 1425,
    stock: 500,
    stockHealth: 'overstock',
    type: 'evergreen',
    salesTrend: 'down',
    turnoverDays: 37,
    marginRate: 0.70,
    fieldMix: { creatorContent: 30, sellerContent: 25, shopTab: 25, search: 20 },
    isStar: false,
  },
  {
    id: 'insta_007',
    name: 'Pro 备用电池套装',
    price: 59,
    cost: 29,
    weeklySales: 36,
    weeklyGMV: 2124,
    stock: 85,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 16,
    marginRate: 0.50,
    fieldMix: { creatorContent: 40, sellerContent: 30, shopTab: 20, search: 10 },
    isStar: false,
  },
  {
    id: 'insta_008',
    name: 'ND 滤镜 6件套',
    price: 39,
    cost: 17.5,
    weeklySales: 12,
    weeklyGMV: 468,
    stock: 150,
    stockHealth: 'overstock',
    type: 'testing',
    salesTrend: 'down',
    turnoverDays: 88,
    marginRate: 0.55,
    fieldMix: { creatorContent: 60, sellerContent: 15, shopTab: 15, search: 10 },
    isStar: false,
  },
]

export const techgadgetSkus: SkuData[] = [
  {
    id: 'tg_001',
    name: '15W 无线充电板',
    price: 25,
    cost: 15,
    weeklySales: 18,
    weeklyGMV: 450,
    stock: 120,
    stockHealth: 'overstock',
    type: 'evergreen',
    salesTrend: 'down',
    turnoverDays: 47,
    marginRate: 0.40,
    fieldMix: { creatorContent: 20, sellerContent: 25, shopTab: 30, search: 25 },
    isStar: false,
  },
  {
    id: 'tg_002',
    name: 'USB-C 快充线 3条装',
    price: 12,
    cost: 4.8,
    weeklySales: 35,
    weeklyGMV: 420,
    stock: 200,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 40,
    marginRate: 0.60,
    fieldMix: { creatorContent: 30, sellerContent: 20, shopTab: 30, search: 20 },
    isStar: true,
  },
  {
    id: 'tg_003',
    name: '车载手机支架',
    price: 18,
    cost: 9,
    weeklySales: 14,
    weeklyGMV: 252,
    stock: 45,
    stockHealth: 'low',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 22,
    marginRate: 0.50,
    fieldMix: { creatorContent: 15, sellerContent: 20, shopTab: 35, search: 30 },
    isStar: false,
  },
  {
    id: 'tg_004',
    name: '10000mAh 超薄充电宝',
    price: 29,
    cost: 18.8,
    weeklySales: 12,
    weeklyGMV: 348,
    stock: 30,
    stockHealth: 'low',
    type: 'seasonal',
    salesTrend: 'up',
    turnoverDays: 18,
    marginRate: 0.35,
    fieldMix: { creatorContent: 60, sellerContent: 15, shopTab: 15, search: 10 },
    isStar: false,
  },
  {
    id: 'tg_005',
    name: '蓝牙音频接收器',
    price: 15,
    cost: 8.2,
    weeklySales: 6,
    weeklyGMV: 90,
    stock: 80,
    stockHealth: 'overstock',
    type: 'evergreen',
    salesTrend: 'down',
    turnoverDays: 93,
    marginRate: 0.45,
    fieldMix: { creatorContent: 10, sellerContent: 20, shopTab: 40, search: 30 },
    isStar: false,
  },
]

export const bnkerSkus: SkuData[] = [
  {
    id: 'bnk_001',
    name: 'TWS 真无线降噪耳机 Pro',
    price: 79,
    cost: 47,
    weeklySales: 200,
    weeklyGMV: 15800,
    stock: 600,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 21,
    marginRate: 0.40,
    fieldMix: { creatorContent: 55, sellerContent: 25, shopTab: 15, search: 5 },
    isStar: true,
  },
  {
    id: 'bnk_002',
    name: '20W USB-C 快充头',
    price: 15,
    cost: 7.5,
    weeklySales: 480,
    weeklyGMV: 7200,
    stock: 1500,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 22,
    marginRate: 0.50,
    fieldMix: { creatorContent: 35, sellerContent: 25, shopTab: 25, search: 15 },
    isStar: true,
  },
  {
    id: 'bnk_003',
    name: '65W 氮化镓双口充电器',
    price: 39,
    cost: 21.5,
    weeklySales: 240,
    weeklyGMV: 9360,
    stock: 400,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 12,
    marginRate: 0.45,
    fieldMix: { creatorContent: 50, sellerContent: 30, shopTab: 15, search: 5 },
    isStar: true,
  },
  {
    id: 'bnk_004',
    name: '20000mAh 双向快充充电宝',
    price: 35,
    cost: 21.7,
    weeklySales: 160,
    weeklyGMV: 5600,
    stock: 300,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 13,
    marginRate: 0.38,
    fieldMix: { creatorContent: 45, sellerContent: 20, shopTab: 20, search: 15 },
    isStar: false,
  },
  {
    id: 'bnk_005',
    name: '7合1 USB-C Hub',
    price: 49,
    cost: 28.5,
    weeklySales: 100,
    weeklyGMV: 4900,
    stock: 180,
    stockHealth: 'healthy',
    type: 'seasonal',
    salesTrend: 'up',
    turnoverDays: 13,
    marginRate: 0.42,
    fieldMix: { creatorContent: 60, sellerContent: 20, shopTab: 15, search: 5 },
    isStar: false,
  },
  {
    id: 'bnk_006',
    name: 'ANC 头戴式降噪耳机',
    price: 129,
    cost: 80,
    weeklySales: 72,
    weeklyGMV: 9288,
    stock: 200,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 19,
    marginRate: 0.38,
    fieldMix: { creatorContent: 50, sellerContent: 25, shopTab: 20, search: 5 },
    isStar: false,
  },
  {
    id: 'bnk_007',
    name: '无线耳机 Lite 青春版',
    price: 39,
    cost: 25.3,
    weeklySales: 100,
    weeklyGMV: 3900,
    stock: 450,
    stockHealth: 'overstock',
    type: 'testing',
    salesTrend: 'down',
    turnoverDays: 32,
    marginRate: 0.35,
    fieldMix: { creatorContent: 40, sellerContent: 30, shopTab: 20, search: 10 },
    isStar: false,
  },
  {
    id: 'bnk_008',
    name: '45W 车载快充头',
    price: 25,
    cost: 13,
    weeklySales: 120,
    weeklyGMV: 3000,
    stock: 250,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'stable',
    turnoverDays: 15,
    marginRate: 0.48,
    fieldMix: { creatorContent: 25, sellerContent: 25, shopTab: 30, search: 20 },
    isStar: false,
  },
  {
    id: 'bnk_009',
    name: '3米编织快充线',
    price: 12,
    cost: 4.8,
    weeklySales: 350,
    weeklyGMV: 4200,
    stock: 1200,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 24,
    marginRate: 0.60,
    fieldMix: { creatorContent: 30, sellerContent: 20, shopTab: 30, search: 20 },
    isStar: false,
  },
  {
    id: 'bnk_010',
    name: '磁吸桌面手机支架',
    price: 22,
    cost: 9.9,
    weeklySales: 140,
    weeklyGMV: 3080,
    stock: 350,
    stockHealth: 'healthy',
    type: 'evergreen',
    salesTrend: 'up',
    turnoverDays: 18,
    marginRate: 0.55,
    fieldMix: { creatorContent: 45, sellerContent: 25, shopTab: 20, search: 10 },
    isStar: false,
  },
]

export function getSkusByMerchantId(merchantId: string): SkuData[] {
  const map: Record<string, SkuData[]> = {
    merchant_001: insta365Skus,
    merchant_002: techgadgetSkus,
    merchant_003: bnkerSkus,
  }
  return map[merchantId] ?? []
}
